sudo: false
language: php

php:
- 7.1
- 7.2
- nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install: travis_retry composer update --prefer-dist

script:
  - vendor/bin/phpcs

stages:
  - Validate against schema
  - Test

jobs:
  allow_failures:
    - php: nightly

  include:
    - stage: Validate against schema
      addons:
        apt:
          packages:
          - libxml2-utils
      script: xmllint --noout --schema vendor/squizlabs/php_codesniffer/phpcs.xsd src/ZendCodingStandard/ruleset.xml

notifications:
  email: false
